config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "articles#index"

  resources :articles do
    resources :comments
    delete 'delete_attachment/:id', to: 'articles#delete_attachment', as: :delete_attachment
    post 'publish', to: 'articles#publish'
  end
  get 'my/articles', to: 'articles#my_articles'
  get 'articles-to-publish', to: 'articles#submitted_article'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Flipper::UI.app(Flipper) => '/flipper'
end

app/models/Article.rb
class Article < ApplicationRecord
  has_many :comments

  validates :title, presence: true, length: { minimum: 4 }
  validates :body, presence: true, length: { minimum: 4 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include AASM

  has_many :comments, dependent: :destroy
  belongs_to :user

  # Active storage configuration
  has_many_attached :attachments

  aasm column: :state do # default column: aasm_state
    state :draft, initial: true
    state :submit, :publish

    event :submitting do
      transitions from: :draft, to: :submit
    end

    event :publishing do
      transitions from: :submit, to: :publish
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_ancestry ancestry_column: :manager_id

  has_many :articles, dependent: :destroy

  enum role: { admin: "admin", user: "user" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :role, :password, :manager_id) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :role, :password, :current_password, :manager_id)}
  end
end

app/controllers/articles_controller.rb
require 'ArticleContract'

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /articles
  def index
    @pagy, @articles = pagy_countless(Article.publish, link_extra: 'data-remote="true"')
  end

  # GET /articles/1
  def show
    @page = params[:page]
    @page_back = params[:page_back]
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    contract = Contract::ArticleContract.new

    respond_to do |format|
      validation_result = contract.call(title: article_params[:title], body: article_params[:body])
      if validation_result.success?
        @article = Article.new(article_params)
        @article.user_id = current_user.id
        @article.submitting if params[:state] == 'Submit'
        @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        @errors = validation_result.errors.to_h
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  def update
    respond_to do |format|
      contract = Contract::ArticleContract.new
      validation_result = contract.call(title: article_params[:title], body: article_params[:body])

      if validation_result.success?
        @article.submitting if params[:state] == 'Submit'
        @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        @errors = validation_result.errors.to_h
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  def delete_attachment
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge
    respond_to do |format|
      format.html { redirect_to article_url(params[:article_id]), notice: 'Attachment was successfully destroyed.' }
    end
  end

  def my_articles
    @pagy, @articles = pagy(Article.where('user_id=?', current_user.id))
  end

  def submitted_article
    if Flipper[:publish].enabled? current_user
      children = User.find(current_user.id).children.select('id').to_a
      @pagy, @articles = pagy(Article.where('user_id IN (?)', children.each(&:id)))
    else
      redirect_to root_path, notice: 'Feature is disabled'
    end
  end

  def publish
    article = Article.find(params[:article_id])
    article.publishing!
    respond_to do |format|
      format.html { redirect_to articles_to_publish_url, notice: 'Successfully published an article.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, attachments: [])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, html: { multipart: true }) do |form| %>
  <% if errors %>
    <div id="error_explanation">
      <h2><%= pluralize(errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% errors.each do |key, messages| %>
        <li><%= "#{key} #{messages.join(', ')}" %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="attachments">
    <%= form.label :attachments %>
    <% article && article.attachments.each do |attachment|%>
      <div>
        <%= image_tag attachment.variant(resize: '100x100') %>
        <%= link_to 'Remove', article_delete_attachment_url(@article.id, attachment),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>

  <%= form.file_field :attachments, multiple: true %>

  <div class="actions">
    <%= form.submit 'Save as drafts' %>
    <%= form.submit 'Submit', name: 'state' %>
  </div>
<% end %>

app/views/articles/_next_link.html.erb
<%== pagy_next_link(@pagy, 'More...', 'id="next_link" style="display: none;"') %>

app/views/articles/_page_items.html.erb
<% @articles.each do |article| %>
<tr>
  <td scope="row"><%= article.id %></th>
  <td><%= article.title %></td>
  <td><%= article.body %></td>
  <td>
    <%= link_to 'Show', article_path(article, page: 'articles', page_back: articles_path) %>
  </td>
</tr>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article, errors: @errors %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', my_articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table id="records_table" class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Body</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'page_items' %>
  </tbody>
</table>

<div id="div_next_link">
  <%= render partial: 'next_link' %>
</div>

<%= link_to 'New Article', new_article_path %>
<%= link_to 'My Articles', my_articles_path %>
<% if Flipper[:publish].enabled? current_user %>
  <%= link_to 'Publish Articles', articles_to_publish_path %>
<% end %>

<% content_for :page_scripts do %>
<script>
  function loadNextPage() {
    if ($('#next_link').data("loading")) {
      return;
    }
    // prevent multiple loading
    const wBottom = $(window).scrollTop() + $(window).height();
    const elBottom = $('#records_table').offset().top + $('#records_table').height();

    if (wBottom > elBottom) {
      const nextLink = $('#next_link');
      if (nextLink.length === 0) {
        return;
      }
      nextLink[0].click();
      nextLink.data("loading", true);
    }
  };

  document.addEventListener('resize', loadNextPage);
  document.addEventListener('scroll', loadNextPage);
  document.addEventListener('load', loadNextPage);
</script>
<% end %>

app/views/articles/index.js.erb
$('#records_table tbody').append("<%= j(render 'page_items')%>");
$('#div_next_link').html("<%= j(render 'next_link') %>");

app/views/articles/my_articles.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Home', root_path %>
<h1>My Articles</h1>

<table id="records_table" class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Body</th>
    <th>State</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td scope="row"><%= article.id %></th>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= article.state %></td>
      <td>
        <%= link_to 'Show', article_path(article, page: 'my-articles', page_back: my_articles_path) %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Article', new_article_path %>

<%== pagy_nav(@pagy) %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article, errors: @errors %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Attachment:</strong>
  <% @article.attachments.each do |attachment|%>
    <%= image_tag attachment.variant(resize: '100x100') %>
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.email %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form', article: @article %>

<% if @page == 'publish' %>
  <%= link_to 'Publish', article_publish_path(@article), method: :post %>
<% elsif @page == 'my-articles' %>
    <%= link_to 'Edit', edit_article_path(@article) %>
<% end %>
<%= link_to 'Back', @page_back %>

app/views/articles/submitted_article.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Home', root_path %>

<h1>Articles to publish</h1>

<table id="records_table" class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Body</th>
    <th>User</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td scope="row"><%= article.id %></th>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= article.user.name || article.user.email %></td>
      <td>
        <%= link_to 'Show', article_path(article, page: 'publish', page_back: articles_to_publish_path) %>
        <%= link_to 'Publish', article_publish_path(article), method: :post %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ article, article.comments.build], local: true) do |form| %>
<!--  <p>-->
<!--    <%#= form.label :commenter %><br>-->
    <%#= form.text_field :commenter %>
<!--  </p>-->
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :page_scripts %>
  </head>

  <body>
    <% if current_user %>
      <div class="user-details">
        <%= current_user.name || current_user.email %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger' %>
      </div>
    <% end %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>